### ISSUE TITLE
pagina principal y detalle 10 min

### ISSUE THREAD

**Issue by dbistuer** [sergiobeltranguerrero/Shoeslab#22]
Añadimos la estructura de el inicio con los menus, perfil y carrito.
 Dispondremos de un filtro de zapatos y ordenación de precio. Cada zapato dispondra de imagen texto breve descripción

![Image](https://user-images.githubusercontent.com/76478652/236219897-2bbbafa5-7c7a-420c-a289-5af623629e12.png)

Una vez seleccionado el zapato veremos la imagen una descripción mas completa. Podremos guardarlos añadir al carrito o personalizarlos.

![Image](https://user-images.githubusercontent.com/76478652/236220195-8eeac09d-f673-4e0d-b35d-468c35a644d8.png)

**Comment by aaron-at97** [comment]
ok

**Comment by aaron-at97** [comment]
diseño

**Comment by aaron-at97** [comment]
Diseño zapatos 

![Image](https://user-images.githubusercontent.com/76478652/236225720-07df4574-9053-42c5-b570-870d4e4ecb8b.png)
