### ISSUE TITLE
Logo web (20 min)

### ISSUE THREAD

**Issue by dbistuer** [sergiobeltranguerrero/Shoeslab#3]

**Comment by rescoda7** [comment]
![Image](https://user-images.githubusercontent.com/76744462/236219034-62432c89-6387-4bd4-84a6-a40a43ca6558.jpeg)

**Comment by rescoda7** [comment]
El cliente ha decidido incorporar los colores verde y azul en el logo de la web.

**Comment by rescoda7** [comment]
Justificación del logo elegido:

1. Simplicidad y legibilidad: Un logo redondo puede ser una forma fácil de destacar un diseño, ya que su forma simple y equilibrada lo hace fácil de leer y reconocer. Además, al colocar los elementos dentro del círculo, se crea una sensación de cohesión y unidad en el diseño.

2. Identificación de la marca: Al incluir dos zapatos en el centro del diseño, se crea una imagen instantánea y memorable que hace que los espectadores asocien el logo con la venta de zapatillas. Esta es una forma efectiva de identificar rápidamente la marca en la mente de los consumidores.

3. Información clara: La inclusión del nombre de la tienda en la parte superior y el eslogan en la parte inferior del logo proporciona información clara y concisa sobre la marca y lo que representa. Esto hace que el logo sea más fácil de entender y recordar para los consumidores.
